# Generated by Django 3.0.3 on 2020-04-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Profile_Site',
            new_name='portfolio_site',
        ),
    ]
